---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: 2.0.0-SNAPSHOT
    app.kubernetes.io/name: camel-quarkus-dbz-native
  name: camel-quarkus-dbz-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 2.0.0-SNAPSHOT
      app.kubernetes.io/name: camel-quarkus-dbz-native
  template:
    metadata:
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 2.0.0-SNAPSHOT
        app.kubernetes.io/name: camel-quarkus-dbz-native
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: camel-quarkus-dbz-configuration
          image: quay.io/ryanezil/camel-quarkus-dbz-native:2.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: camel-quarkus-dbz-native
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - name: jslt-mappers-cm
              readOnly: true
              mountPath: /jslt-mappers
      volumes:
        - name: jslt-mappers-cm
          configMap:
            name: jslt-mappers-cm
            defaultMode: 420
