apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  primary.cnf: |
    [mariadb]
    server-id         = 654321
    log_bin           = mysql-bin
    binlog_format     = ROW
    binlog_row_image  = FULL
    expire_logs_days  = 10