---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-single-node-cluster
  annotations:
    description: "AMQ Streams - Kafka Connect cluster"
  # Annotation 'use-connector-resources' configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.6.0
  build:
    output:
      # Use type 'docker' to push built image into a container registry like Docker Hub or Quay.io
      type: imagestream
      image: my-kafka-connect-image:0.0.1
    plugins:
    - name: debezium-connector-mysql
      artifacts:
      - type: zip
        url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-mysql/2.3.7.Final-redhat-00001/debezium-connector-mysql-2.3.7.Final-redhat-00001-plugin.zip
        sha512sum: dc932541c5d56774cd754a586d94b22fa56296fff715b78cfee39d0131df5a1b55dabf884917b475c9d11bdfc086b0d2c1b6c97e7fd1888b4d577d9f06492c59
      - type: zip
        url: https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-distro-connect-converter/2.5.5.Final-redhat-00001/apicurio-registry-distro-connect-converter-2.5.5.Final-redhat-00001.zip
        sha512sum: 65f6a150feb29c3fff13b0b6e31e135c56df83e47bbd91b296abf08b4ce444e71c96189e68cb845bc11003716cf2969aea46ecfc471f612aa221cf2efd4c2b44




  replicas: 1
  bootstrapServers: single-node-cluster-kafka-bootstrap:9092
#  authentication:
#    type: scram-sha-512
#    username: superuser
#    passwordSecret:
#      secretName: superuser
#      password: password
#  tls:
#    trustedCertificates:
#      - secretName: single-node-cluster-cluster-ca-cert
#        certificate: ca.crt
  config:
    group.id: my-kconnect-cluster-groupid
    # Default value is TRUE when topic autocreation is not set:
    topic.creation.enable: "true"
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1

  logging:
#    type: external
#    valueFrom:
#      configMapKeyRef:
#        name: logging-config-cm
#        key: logging.properties
    type: inline
    loggers:
      log4j.rootLogger: INFO
      log4j.logger.io.debezium.connector.mongodb: TRACE
  resources:
#    requests:
#      cpu: 500m
#      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  readinessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 30
  livenessProbe:
    initialDelaySeconds: 180
    timeoutSeconds: 30
